name: build-and-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app into ./dist/browser
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          # Ensure the Angular build writes the browser output directly into dist/browser
          # Use npx to call the Angular CLI and use `--configuration=production` (explicit '=')
          npx ng build --configuration=production --output-path=dist/browser --base-href "/${REPO_NAME}/"

      - name: Show dist contents (for debugging)
        run: |
          echo "Listing dist/ contents:"
          ls -la dist || true
          echo "Listing dist/browser contents (if present):"
          ls -la dist/browser || true
          echo "---- index.html head (dist/browser/browser/index.html if present) ----"
          head -n 60 dist/browser/browser/index.html || true

      - name: Configure git identity for gh-pages commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Prepare publish directory and 404 fallback
        run: |
          set -e
          # Try known build output locations and copy to a clean publish/ dir
          rm -rf publish || true
          mkdir publish

          if [ -f dist/index.html ]; then
            echo "Using dist/"
            cp -r dist/* publish/
          elif [ -f dist/browser/index.html ]; then
            echo "Using dist/browser/"
            cp -r dist/browser/* publish/
          elif [ -f dist/browser/browser/index.html ]; then
            echo "Using dist/browser/browser/"
            cp -r dist/browser/browser/* publish/
          else
            echo "No index.html found in expected locations; listing dist for debugging" && ls -R dist || true
            exit 0
          fi

          # Ensure 404.html exists for client-side routing
          if [ -f publish/index.html ]; then
            cp publish/index.html publish/404.html || true
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
          keep_files: false
          commit_message: "chore: deploy site from GitHub Actions"